name: DonjonRL
version: 1.0
author: EazyEnder
main : fr.eazyender.donjon.DonjonMain
commands:
  gspell:
    description: Give de spell
    permission: admin.use
    alisases: gsp
  gweapon:
    description: Give weapons
    permission: admin.use
    alisases: gwp
  gpotion:
    description: Give potions
    permission: admin.use
    alisases: gp
  money:
    description: Check Money
    permission: player.use
  chromatique:
    description: Open Chromatiques GUI
    permission: player.use
  group:
    description: Add a friend to your group
    permission: player.use
    aliases: friend
  accept:
    description: Accept friend request
    permission: player.use
    aliases: yes
  npc:
    description: Spawn a custom NPC
    permission: admin.use
  holo:
    description: Spawn a holo
    permission: admin.use